name: md_toast
version: 1.0.0
description: A Material Design Toast component for AngularDart
author: John Ryan <john.ryan@apptreesoftware.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  build_runner: ">=0.10.3 <2.0.0"
  build_web_compilers: ^0.4.0
  angular: ^5.0.0

dev_dependencies:
  angular_components: any
  test: ^1.0.0

